sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.6"
branches:
  only:
  - /^\d+\.\d+\.\d+$/
script:
  - python setup.py sdist bdist_wheel
  - twine upload dist/*.tar.gz
before_script:
  - pip install -U twine setuptools
