sudo: false
language: python
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- '3.6'
branches:
  only:
  - "/^\\d+\\.\\d+\\.\\d+$/"
script: true
deploy:
  provider: pypi
  user: ShagaleevAlexey
  password:
    secure: Xez/CVrzSCDAy6whqRlbY8l3tbLDjnsN2oWWUfcIw1D6Z/crVZcNYH5YpuYcW78nFt7ANfy8jMrXOBhpZGlmgP4ZXSy1vCLJwGCs0l0YkC2U9SLdYClpAhVwRr4M0mKp9u4a3vrUcNLzghnlK9Hj+Ey4/H1CSPYeuFPgn98JxCfRyb4UwQeuVYAsp7spiIAMI5z7DZk4nJb0CLsTaAk549I27odHyfy89PYQEf9/0Fq37R39KvethbssmErYYjMBpoNUdjK2Ly5bdZpbkJCcLkAB3orweXSiRcogiciLB+MOlUcHa8+Mr4G9yxB5VrNwWkPZaeXPPVLtTe5mz1KFKdDulGfZhJpkUjJk7zDqSpZg389WPMU79mNhuotZ5JrXLiMuKIz3OOWyvKJwMVDPd+ATqYKzVtis2hu/BQSSkF3by/ikonXbZe9Y1j586Be63/hgnafHXIJ9UWmEfBHyTQH4S6m4KELe3dmqx1bIYIROncifEYE0B90054TesraLFVL+P5gZDEqZdOO38Yix2fsvlDMnuv3vMmMVSQC2+jC5hwBzsnm6Sz+307F7uOBeLNbp5XfQObYe/tklB8XJeS/ilMK9tgTBXAuXHCf3cVLY5XU19JbQpfT+/e4qYolX4QEH0fULWNnulO0K45sMgshy/KJLw5bQqB+29uMzmc8=
  on:
    tags: true
  distributions: sdist bdist_wheel
