dist: xenial
language: python
python:
  - "3.6"
virtualenv:
  system_site_packages: true
branches:
  only:
  - /^\d+\.\d+\.\d+$/
script:
  - python setup.py sdist
  - twine upload dist/*.tar.gz
before_script:
  - pip install -U twine setuptools
